version: '3'
services:
  api-whatsweb:
    container_name: api-whatsweb
    image: api-whatsweb:latest
    restart: always
    volumes:
      - ./profiles:/app/profiles
      - ./prints:/app/prints
      - ./.env:/app/.env
      # - ./code/whatsweb_interactions.py:/app/code/whatsweb_interactions.py # DEBUG
    environment:
      - TZ=America/Sao_Paulo
      - VALID_PROFILE_PATH=/app/profiles
      - VALID_PRINTS_PATH=/app/prints
      - CAIXA_DE_PESQUISA=//div[@aria-label="Pesquisar"]//p[contains(@class, "selectable-text")]
      - CAIXA_MENSAGEM=//div[@aria-label="Digite uma mensagem"]
      - BOTAO_ENVIAR=//span[@data-icon="send"]
    ports:
      - 8910:80