version: '3'
services:
  api-whatsweb:
    container_name: api-whatsweb
    image: api-whatsweb:latest
    restart: always
    volumes:
      - ./profiles:/app/profiles
      - ./prints:/app/prints
      - ./.env:/app/.env
      - ./code/whatsweb_interactions.py:/app/code/whatsweb_interactions.py
    ports:
      - 8000:80