version: '3'
services:
  api-whatsweb:
    container_name: api-whatsweb
    image: api-whatsweb:latest
    restart: always
    volumes:
      - ./profiles:/app/profiles
      - ./prints:/app/prints
      - ./.env:/app/.env
      # - ./code/whatsweb_interactions.py:/app/code/whatsweb_interactions.py # DEBUG
    environment:
      - TZ=America/Sao_Paulo
      - VALID_PROFILE_PATH=/app/profiles
      - VALID_PRINTS_PATH=/app/prints
    ports:
      - 8000:80