services:
  api-whatsweb:
    container_name: api-whatsweb
    build: .
    restart: always
    network_mode: host
    volumes:
      - ./profiles:/app/profiles
      - ./prints:/app/prints
      - ./.env:/app/.env
      # - ./code/whatsweb_interactions.py:/app/code/whatsweb_interactions.py # DEBUG
    environment:
      - TZ=America/Sao_Paulo
      - CAIXA_DE_PESQUISA=//div[@id="side"]//div[@aria-owns="emoji-suggestion"]//p
      - CAIXA_MENSAGEM=//footer//div[@aria-owns="emoji-suggestion"]//p
      - BOTAO_ENVIAR=//button[@aria-label="Enviar"]//span
    # ports:
    #   - 8910:80

  api-calls:
    container_name: api-calls
    image: python:3.11.10
    network_mode: host
    volumes:
      - ./calls/:/calls/
      - ./requirements.txt:/requirements.txt
    env_file:
      - pass.env
    environment:
      - TZ=America/Sao_Paulo
    command: bash -c "pip install -r requirements.txt && python calls/main.py"
    # command: bash -c "pip install requests && python app/bonus_news.py"
