version: '3'
services:
  api-whatsweb:
    container_name: api-whatsweb
    image: api-whatsweb:latest
    restart: always
    volumes:
      - ./profiles:/app/profiles
      - ./prints:/app/prints
      - ./.env:/app/.env
      # - ./code/whatsweb_interactions.py:/app/code/whatsweb_interactions.py # DEBUG
    environment:
      - TZ=America/Sao_Paulo
      - VALID_PROFILE_PATH=/app/profiles
      - VALID_PRINTS_PATH=/app/prints
      - CAIXA_DE_PESQUISA=//div[@aria-label="Pesquisar"]//p[contains(@class, "selectable-text")]
      - CAIXA_MENSAGEM=//div[@aria-label="Digite uma mensagem"]
      - BOTAO_ENVIAR=//span[@data-icon="send"]
    ports:
      - 8910:80

  api-calls:
    container_name: api-calls
    image: python:3.11.10
    restart: always
    volumes:
      - ./calls/:/calls/
      - ./requirements.txt:/requirements.txt
    env_file:
      - pass.env
    environment:
      - TZ=America/Sao_Paulo
    command: bash -c "pip install -r requirements.txt && python calls/main.py"
    # command: bash -c "pip install requests && python app/bonus_news.py"
